# Create a workflow to build java application with maven
# https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Java CI with Maven

# Trigger the workflow on push or pull request, and manually on main branch
on:
  workflow_dispatch:

# Create the job to build on Java 17
jobs:
  build:

    # Use Ubuntu 20.04 as the virtual machine
    runs-on: ubuntu-20.04

    # Use JDK 17
    strategy:
      matrix:
        java: [ 17 ]

    # Steps to execute
    steps:
    - uses: actions/checkout@v3
    # - name: Set up JDK ${{ matrix.java }}
    #   uses: actions/setup-java@v3
    #   with:
    #     java-version: ${{ matrix.java }}
    #     distribution: 'adopt'
    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml

    - name: run gh cli
      run: |
        gh issue create --title "Demo" --body "This issue is created by running gh cli"

        # GitHub CLI api

        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/pulls \
          -f title='Amazing new feature' \
         -f body='Please pull these awesome changes in!' \
         -f head='gh-cli' \
         -f base='main' 
      env:
        GH_TOKEN: ${{ github.token }}







